# Generated by Django 6.0 on 2026-01-02 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Book Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('cover_image', models.ImageField(upload_to='books/', verbose_name='Cover Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible on site')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(help_text='e.g. Amazon, FNAC, Publisher', max_length=50, verbose_name='Platform Name')),
                ('url', models.URLField(verbose_name='URL')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='portfolio.book')),
            ],
            options={
                'verbose_name': 'Purchase Link',
                'verbose_name_plural': 'Purchase Links',
            },
        ),
    ]
